### ISSUE TITLE
Sample app does not work on php 5.3.25

### ISSUE THREAD

**Issue by rohan589** [googleplus/gplus-quickstart-php#13]
Hi,

I used the code from the sample app on a server with PHP 5.4 and that worked just fine. Turns out the code just won't work on the production server which has PHP 5.3.25. The sample app does not run on it. The page does not load (http://beta.magicmarks.in/google/signin.php) Chrome console shows an error 'Failed to load resource: net::ERR_EMPTY_RESPONSE'.

My gut feeling is that it's just that the library requires PHP 5.4 or higher. But then I tried it on two other servers with 5.3.20 and 5.3.3 and they worked fine. The requirements stated here are 5.3 or higher so i guess 5.3.25 should be supported. I'm quite clueless what's wrong. I've tried enabling the curl extension as well.

Upgrading the PHP in production is a long process so that's my last resort if nothing else works.

Any advice would be much appreciated!

**Comment by mirko77** [comment]
I am on PHP 5.6.2, just a blank screen, no errors in console...

**Comment by gguuss** [comment]
Working for me on PHP 5.5 - make sure you follow the instructions here: https://developers.google.com/+/web/samples/php

**Comment by gguuss** [comment]
Closing stale issue.
