### ISSUE TITLE
Pure PHP example

### ISSUE THREAD

**Issue by HMAZonderland** [googleplus/gplus-quickstart-php#14]
Its kinda useless using Twig and Silex. Why isn't there a pure PHP example?

**Comment by ptdev** [comment]
:+1: c^2

**Comment by darkoverlordofdata** [comment]
Yes please create a pure php example. The login part is working, but the example is failing on rendering templates. I'm trying to debug Twig and Silex in netbeans and getting nowhere. I can't tell if it's the libraries or the demo that I'm having problems with.

**Comment by gguuss** [comment]
Acknowledged, thanks for letting us know this is important.

**Comment by audas** [comment]
Honestly - Google should be ashamed of this crap.

This is the only information on accessing Google+ with PHP from their own docs - a link to 4 year old file which simply does not work, is based on useless third party libraries.

Like it or not PHP is the biggest language on the web - Google has completely ignored it - and so everyone has ignored Google+.

Google+ will be shut down - and this is why. Absolutely absurd behaviour.

There is literally no information on how to set up an account to post from a web api to a google plus account - none.

Mind blown.

**Comment by ptdev** [comment]
Ha! Had forgotten about this issue.

Q: How many Google engineers are needed to create a usable php sample?
A: Over 72052 (https://abc.xyz/investor/pdf/20161231_alphabet_10K.pdf)

I'm with you @audas, Google+ must surely be close to death so I wouldn't even bother with this crap anymore.

**Comment by HMAZonderland** [comment]
Let me close this issue as its totally not relevant anymore.
