### ISSUE TITLE
User login information

### ISSUE THREAD

**Issue by AnowarCST** [googleplus/gplus-quickstart-php#16]
Hi,
I've implement this code into my localhost. 
But I can't get the user login information. I've to write this data into my SESSION variable for login. 
Please help me to get user information like name,email, contact no etc in PHP.

Thanks in advance.

**Comment by gguuss** [comment]
Make sure you follow the instructions here: https://developers.google.com/+/web/samples/php

Of note, you must install PHP composer and install the project dependencies before invoking the local php server.

**Comment by AnowarCST** [comment]
Yes I got it.
Thanks :) @gguuss
