### ISSUE TITLE
Php Fatal Error Class 'Google_Service_Plus' not found in signin.php

### ISSUE THREAD

**Issue by syedali7** [googleplus/gplus-quickstart-php#19]
Hi folks,

This is error I am getting, not found this 'Google_Service_Plus' class anywhere in the vendor directory.

Autoload.php file is loaded, and not found relevant answers in stackoverflow.
 
Can some help me to fix this bug

Thanks
Ali

**Comment by gguuss** [comment]
I'm guessing the PHP library has changed, we recently made a change to force use of v1-master, which should have fixed this.

**Comment by syedali7** [comment]
Gguuss, thank you very much for your reply, can you give me link where can I download

Thanks
Ali
