### ISSUE TITLE
JavaScript don't retrieve your profile

### ISSUE THREAD

**Issue by giuliarnhold** [googleplus/gplus-quickstart-php#21]
When I sign up with my Google + account in the page signin.php nothing happens. Theoretically the application uses the JavaScript client to retrieve your profile and uses the PHP client library to retrieve the people visible to the app. but this is not happening.

**Comment by gguuss** [comment]
@giuliarnhold Can you provide more information like PHP version, browser version, and any errors you are seeing from PHP or the JavaScript console?

**Comment by radioblahaj** [comment]
Even If, It has been a long time, i still see this issue. @gguuss

**Comment by gguuss** [comment]
Crazy, I just recently checked and it's working for me.  There's a lot of variables that could block you from successfully running the sample.

**Comment by radioblahaj** [comment]
Okay, Maybe I Had SOmething on. Thanks!
